#!/usr/bin/env python


import os
import sys

sys.path.append(os.path.dirname(sys.argv[0]))
sys.path.append('/usr/share/mfgames-media')
sys.path.append('/usr/local/share/mfgames-media')

import mfgames.media.mplayer


if __name__ == "__main__":
    mfgames.media.mplayer.do_mplayer_tool(sys.argv[1:])
