#!/usr/bin/env python

"""Script for processing Amarok data."""


import argparse
import logging
import os
import sys

sys.path.append(os.path.dirname(sys.argv[0]))
sys.path.append('/usr/share/mfgames-media')
sys.path.append('/usr/local/share/mfgames-media')

import mfgames.media.amarok


LOG_FORMAT = "%(asctime)-15s %(message)s"

processes = {
    'pack' : mfgames.media.amarok.PackProcess(),
    }


def do_amarok_tool(arguments):
    # Set up the primary parser.
    parser = argparse.ArgumentParser(
        description='Manipulate Amarok files.')

    # Go through the processes and add each one's subparser.
    subparsers = parser.add_subparsers()

    for process_name, process in processes.iteritems():
        # Add this subparser to the primary parser.
        process_parser = subparsers.add_parser(
            process_name,
            help=process.get_help())
        process_parser.set_defaults(name=process_name)

        # Add the process-specific arguments to the parser.
        process.setup_arguments(process_parser)

    # Process the arguments given on the command line.
    args = parser.parse_args(arguments)

    # Set up the logging to use a common format.
    if args.log == None:
        logging.basicConfig(
            format = LOG_FORMAT,
            level = logging.DEBUG)
    else:
        logging.basicConfig(
            format = LOG_FORMAT,
            level = logging.DEBUG,
            filename = args.log)

    # Use the default to figure out the process name which is then
    # used to call the process() method in that Process class.
    selected_name = args.name
    selected_process = processes[selected_name]
    selected_process.process(args)

#
# Entry
#

if __name__ == "__main__":
    do_amarok_tool(sys.argv[1:])
