#!/bin/bash

# Attempt to resolve the filename which may be a MythTV streaming source.
testpath=$(echo "$@")
realpath=$(mfgames-mythtv resolve "$testpath")

# If we successfully found a file, then play it.
if [ $? == 0 ]
then
    mfgames-mplayer play "$realpath"
fi

# TODO: In a perfect world, we would give an error of some sort.